# Use Node.js 18 Alpine as base in Stage 1: Build Stage
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install necessary build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Copy scripts and data
COPY scripts ./scripts
COPY .db ./.db

# Install dependencies
RUN npm install
RUN npm install --save-dev @types/mongoose

# Stage 2: Production Stage
FROM node:18-alpine AS runner

# Create a new user
RUN adduser -D -u 1000 appuser

# Create a directory and set ownership
RUN mkdir -p /app && chown -R appuser:appuser /app

# Set the working directory
WORKDIR /app

# Switch to the user
USER appuser

COPY --from=builder /app ./

# Set environment variables
ENV NODE_ENV=development

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
